language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository
  licenses:
    - '.+'

script:
  - ./gradlew test

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

sudo: false

before_install:
  - chmod +x gradlew
